import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 28 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.55, delay },
})

const STAR = [
  {
    label: 'S — Situation',
    color: '#fca5a5',
    heading: 'SOC teams are drowning in alert noise',
    body: `Modern Security Operations Centers receive 4,000–10,000 alerts per day per analyst. Over 90% are false positives. The average time to detect a real breach is 207 days (IBM Cost of a Data Breach Report). Traditional SIEM tools flag everything but reason about nothing — they require a human analyst to manually triage each alert, correlate network events, and determine response priority. At scale, this is impossible. By the time an analyst confirms a breach, the attacker has had hours or days of uncontested access.`,
  },
  {
    label: 'T — Task',
    color: '#fb923c',
    heading: 'Build an autonomous AI defense system — not another alert dashboard',
    body: `Design a system that ingests raw network traffic in real-time, classifies threats with ML, generates natural-language incident reports automatically, and executes autonomous responses (IP blocking, node isolation, firewall rule updates) without waiting for human triage. The interface had to be cinematic — a live global threat map that makes the invisible attack surface visible to both technical and executive audiences. All within a containerized, reproducible architecture.`,
  },
  {
    label: 'A — Action',
    color: '#4ade80',
    heading: 'Designed a multi-layer autonomous defense pipeline',
    body: `Chose TensorFlow + Isolation Forest for anomaly detection because cyber threats are inherently novel — rule-based systems fail against zero-days. Isolation Forest detects anomalies without needing labeled attack data. Selected Apache Kafka over RabbitMQ because network traffic peaks hit 10,000+ events/second — Kafka's partitioned log architecture handles this without backpressure, while RabbitMQ queues would saturate. Chose Redis for IP reputation lookups — at 10k events/sec, a PostgreSQL SELECT would add 5-20ms per query; Redis delivers <1ms. Used LangChain agents for autonomous response — agents can reason across multiple tools (firewall API, Kubernetes isolation, alert DB) in a single reasoning loop. React + D3 + Mapbox for the visualization layer: D3 for network graph topology, Mapbox for the geolocation attack map.`,
  },
  {
    label: 'R — Result',
    color: '#c4b5fd',
    heading: 'Autonomous threat isolation in <2 seconds from detection',
    body: `The designed architecture targets <2s from packet anomaly detection to autonomous response (IP block + node isolation). Incident reports generated by LangChain agents reduced manual triage documentation to zero — every incident gets a structured natural-language report with attack vector, timeline, and remediation steps automatically. The cinematic threat map provides real-time executive visibility without requiring any security expertise to interpret. Concept project with full architecture specification, UI mockups, and scaffolded backend services.`,
  },
]

const TECH_STACK = [
  {
    category: 'ML & Detection Layer',
    color: '#fca5a5',
    items: [
      {
        name: 'TensorFlow + Isolation Forest',
        why: 'Rule-based detection fails against zero-day threats. Isolation Forest detects anomalies without labeled attack samples',
        role: 'Anomaly detection',
      },
      {
        name: 'Scikit-learn',
        why: 'Complementary classical ML for signature-based detection on known attack patterns — faster than neural nets for known CVEs',
        role: 'Threat classification',
      },
      {
        name: 'LangChain Agents',
        why: 'Agents orchestrate multi-tool reasoning (firewall API + DB query + alert generation) in one chain — impossible with single LLM calls',
        role: 'Autonomous response',
      },
      {
        name: 'GPT-4 / Claude',
        why: 'Generates natural-language incident reports from raw anomaly data — removes the human analyst from the documentation loop',
        role: 'Incident reporting',
      },
    ],
  },
  {
    category: 'Data Pipeline & Backend',
    color: '#fb923c',
    items: [
      {
        name: 'Apache Kafka',
        why: "Chosen over RabbitMQ: network traffic peaks at 10,000+ events/sec. Kafka's partitioned log handles this; RabbitMQ queues would saturate",
        role: 'Event streaming',
      },
      {
        name: 'FastAPI + WebSockets',
        why: 'Async server for streaming threat events to frontend. HTTP polling at 1Hz adds 1000ms latency; WebSockets deliver <50ms',
        role: 'Real-time API',
      },
      {
        name: 'Redis',
        why: 'IP reputation lookups at 10k/sec require <1ms response. PostgreSQL SELECT would add 5-20ms per query at this throughput',
        role: 'Reputation cache',
      },
      {
        name: 'PostgreSQL',
        why: 'Chosen over MongoDB: security incidents have strict relational structure (incidents → events → affected_nodes → responses)',
        role: 'Incident store',
      },
    ],
  },
  {
    category: 'Visualization & Frontend',
    color: '#4ade80',
    items: [
      {
        name: 'React + TypeScript',
        why: "Complex real-time state (live threat nodes, attack arcs, alert counters) requires React's unidirectional data flow and TS type safety",
        role: 'UI framework',
      },
      {
        name: 'D3.js',
        why: 'Force-directed graph for network topology visualization. D3 handles dynamic node/edge updates without full re-renders',
        role: 'Network graph',
      },
      {
        name: 'Mapbox GL',
        why: 'WebGL-based global map with hardware acceleration. Leaflet.js is too slow for animating 100+ simultaneous attack arcs',
        role: 'Threat map',
      },
    ],
  },
  {
    category: 'Infrastructure',
    color: '#c4b5fd',
    items: [
      {
        name: 'Docker + Compose',
        why: 'All services (Kafka, Redis, FastAPI, React) containerized for reproducible deployment across any environment',
        role: 'Containerization',
      },
      {
        name: 'Kubernetes (target)',
        why: 'Node isolation response requires programmatic pod termination — K8s API provides this natively without manual SSH',
        role: 'Orchestration',
      },
    ],
  },
]

const FEATURES = [
  { tag: 'MAP', title: 'Global Threat Map', desc: 'Live world map with animated attack arcs, red threat nodes, and real-time geolocation of attack origins and targets.' },
  { tag: 'AI', title: 'AI Anomaly Reasoning', desc: 'LLMs analyze packet anomalies and generate natural-language incident reports — no analyst required for triage.' },
  { tag: 'SIM', title: 'Attack Simulation', desc: 'Controlled red-team attack simulations run inside isolated sandboxes to stress-test defense configurations.' },
  { tag: 'DEF', title: 'Autonomous Defense Agents', desc: 'AI agents automatically isolate compromised nodes, block malicious IPs, and update firewall rules in real-time.' },
  { tag: 'NET', title: 'Network Reconstruction', desc: 'When segments go dark under attack, Phantom reconstructs the topology and reroutes critical traffic autonomously.' },
  { tag: 'INT', title: 'Incident Intelligence', desc: 'Full timeline reconstruction of every incident — attack vectors, affected assets, AI reasoning, and remediation steps.' },
]

export default function PhantomPage() {
  return (
    <div style={{ backgroundColor: '#050508', minHeight: '100vh', color: '#e2e8f0', position: 'relative', overflow: 'hidden' }}>

      {/* Background */}
      <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 0 }}>
        <div style={{ position: 'absolute', top: '-10%', right: '0%', width: '600px', height: '600px', borderRadius: '50%', background: 'radial-gradient(circle, rgba(239,68,68,0.1) 0%, transparent 65%)', filter: 'blur(60px)' }} />
        <div style={{ position: 'absolute', top: '50%', left: '-5%', width: '400px', height: '400px', borderRadius: '50%', background: 'radial-gradient(circle, rgba(196,165,253,0.07) 0%, transparent 65%)', filter: 'blur(60px)' }} />
        <div style={{ position: 'absolute', bottom: '10%', right: '20%', width: '350px', height: '350px', borderRadius: '50%', background: 'radial-gradient(circle, rgba(251,146,60,0.07) 0%, transparent 65%)', filter: 'blur(60px)' }} />
      </div>

      {/* Sticky header */}
      <div style={{ position: 'sticky', top: 0, zIndex: 10, padding: '20px 40px', borderBottom: '1px solid rgba(239,68,68,0.12)', backdropFilter: 'blur(20px)', backgroundColor: 'rgba(5,5,8,0.85)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Link to="/" style={{ color: '#ef4444', textDecoration: 'none', fontSize: '0.82rem', fontWeight: 700, letterSpacing: '0.04em' }}>
          ← Portfolio
        </Link>
        <span style={{ fontSize: '0.72rem', color: 'rgba(226,232,240,0.35)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>Concept Project · 2025</span>
      </div>

      <div style={{ position: 'relative', zIndex: 1, maxWidth: '900px', margin: '0 auto', padding: '64px 24px 100px' }}>

        {/* Hero */}
        <motion.div {...fadeUp(0)} style={{ marginBottom: '72px' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: '100px', padding: '5px 14px', marginBottom: '20px' }}>
            <motion.span animate={{ opacity: [1, 0.3, 1] }} transition={{ duration: 1.5, repeat: Infinity }}
              style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#ef4444', display: 'inline-block' }} />
            <span style={{ fontSize: '0.68rem', fontWeight: 700, color: '#ef4444', letterSpacing: '0.08em', textTransform: 'uppercase' }}>AI Cyber Defense</span>
          </div>
          <h1 style={{ fontSize: 'clamp(3.5rem, 10vw, 8rem)', fontWeight: 900, letterSpacing: '-0.04em', lineHeight: 0.88, marginBottom: '24px', color: '#f1f5f9' }}>
            PHANTOM
          </h1>
          <p style={{ fontSize: 'clamp(1rem, 2vw, 1.35rem)', fontWeight: 500, color: '#94a3b8', lineHeight: 1.55, maxWidth: '640px', marginBottom: '12px' }}>
            Autonomous AI-powered cybersecurity intelligence — live threat detection, self-healing network defense, and LLM-generated incident analysis at enterprise scale.
          </p>
          <p style={{ fontSize: '0.92rem', color: '#64748b', lineHeight: 1.75, maxWidth: '580px', marginBottom: '32px' }}>
            Built for the next generation of SOC teams. Phantom turns raw network noise into actionable intelligence — autonomously, in real-time, at scale.
          </p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {['TensorFlow', 'Kafka', 'FastAPI', 'Redis', 'LangChain', 'D3.js', 'Mapbox', 'Docker'].map(t => (
              <span key={t} style={{ backgroundColor: 'rgba(239,68,68,0.07)', border: '1px solid rgba(239,68,68,0.18)', borderRadius: '100px', padding: '5px 14px', fontSize: '0.75rem', color: '#fca5a5', fontWeight: 600 }}>
                {t}
              </span>
            ))}
          </div>
        </motion.div>

        {/* Screenshot */}
        <motion.div {...fadeUp(0.1)} style={{ marginBottom: '80px', borderRadius: '20px', overflow: 'hidden', border: '1px solid rgba(239,68,68,0.15)', boxShadow: '0 24px 80px rgba(239,68,68,0.08)' }}>
          <img src="/project-phantom.png" alt="Phantom screenshot" style={{ width: '100%', display: 'block' }} />
        </motion.div>

        {/* STAR */}
        <motion.div {...fadeUp(0.15)} style={{ marginBottom: '80px' }}>
          <div style={{ fontSize: '0.68rem', fontWeight: 700, color: 'rgba(226,232,240,0.35)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '8px' }}>Case Study</div>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 900, color: '#fff', letterSpacing: '-0.03em', marginBottom: '40px', lineHeight: 1.1 }}>
            STAR Framework
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
            {STAR.map(({ label, color, heading, body }, i) => (
              <motion.div key={i} {...fadeUp(0.18 + i * 0.07)}
                style={{ backgroundColor: 'rgba(255,255,255,0.03)', backdropFilter: 'blur(16px)', border: '1px solid rgba(255,255,255,0.06)', borderLeft: `3px solid ${color}`, borderRadius: '16px', padding: '28px 32px' }}>
                <div style={{ fontSize: '0.68rem', fontWeight: 800, color, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '8px' }}>{label}</div>
                <h3 style={{ fontSize: '1.15rem', fontWeight: 700, color: '#f1f5f9', marginBottom: '12px', letterSpacing: '-0.01em' }}>{heading}</h3>
                <p style={{ fontSize: '0.9rem', color: 'rgba(226,232,240,0.65)', lineHeight: 1.8, margin: 0 }}>{body}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Feature grid */}
        <motion.div {...fadeUp(0.2)} style={{ marginBottom: '80px' }}>
          <div style={{ fontSize: '0.68rem', fontWeight: 700, color: 'rgba(226,232,240,0.35)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '8px' }}>Capabilities</div>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 900, color: '#fff', letterSpacing: '-0.03em', marginBottom: '32px', lineHeight: 1.1 }}>
            Core Features
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '14px' }}>
            {FEATURES.map(({ tag, title, desc }) => (
              <div key={title} style={{ backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(239,68,68,0.1)', borderRadius: '16px', padding: '24px' }}>
                <div style={{ fontSize: '0.6rem', fontWeight: 800, letterSpacing: '0.1em', color: '#ef4444', backgroundColor: 'rgba(239,68,68,0.08)', borderRadius: '6px', padding: '3px 8px', display: 'inline-block', marginBottom: '12px' }}>{tag}</div>
                <div style={{ fontWeight: 700, fontSize: '0.95rem', color: '#f1f5f9', marginBottom: '8px' }}>{title}</div>
                <div style={{ fontSize: '0.82rem', color: 'rgba(226,232,240,0.5)', lineHeight: 1.65 }}>{desc}</div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Tech Architecture */}
        <motion.div {...fadeUp(0.25)} style={{ marginBottom: '80px' }}>
          <div style={{ fontSize: '0.68rem', fontWeight: 700, color: 'rgba(226,232,240,0.35)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '8px' }}>Deep Dive</div>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: 900, color: '#fff', letterSpacing: '-0.03em', marginBottom: '16px', lineHeight: 1.1 }}>
            Technical Architecture
          </h2>
          <p style={{ fontSize: '0.9rem', color: 'rgba(226,232,240,0.45)', marginBottom: '40px', lineHeight: 1.7 }}>
            Every technology was chosen to solve a specific performance or scalability constraint.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            {TECH_STACK.map(({ category, color, items }) => (
              <div key={category}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
                  <div style={{ width: '10px', height: '10px', borderRadius: '50%', backgroundColor: color, boxShadow: `0 0 12px ${color}` }} />
                  <span style={{ fontSize: '0.72rem', fontWeight: 800, color, letterSpacing: '0.1em', textTransform: 'uppercase' }}>{category}</span>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '12px' }}>
                  {items.map(({ name, why, role }) => (
                    <div key={name} style={{ backgroundColor: 'rgba(255,255,255,0.03)', backdropFilter: 'blur(12px)', border: `1px solid ${color}18`, borderTop: `2px solid ${color}`, borderRadius: '14px', padding: '20px' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px', gap: '8px' }}>
                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: '#f1f5f9' }}>{name}</div>
                        <span style={{ fontSize: '0.6rem', fontWeight: 700, color, backgroundColor: `${color}12`, borderRadius: '6px', padding: '3px 8px', whiteSpace: 'nowrap', flexShrink: 0 }}>{role}</span>
                      </div>
                      <div style={{ fontSize: '0.78rem', color: 'rgba(226,232,240,0.5)', lineHeight: 1.65 }}>
                        <span style={{ color, fontWeight: 600 }}>Why: </span>{why}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Status */}
        <motion.div {...fadeUp(0.3)}
          style={{ backgroundColor: 'rgba(239,68,68,0.05)', backdropFilter: 'blur(20px)', border: '1px solid rgba(239,68,68,0.15)', borderRadius: '20px', padding: '40px', textAlign: 'center' }}>
          <div style={{ fontSize: '0.68rem', fontWeight: 700, color: '#ef4444', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '12px' }}>Status</div>
          <h3 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#f1f5f9', marginBottom: '10px', letterSpacing: '-0.02em' }}>Architecture Complete · Building MVP</h3>
          <p style={{ fontSize: '0.9rem', color: 'rgba(226,232,240,0.5)', maxWidth: '480px', margin: '0 auto 28px', lineHeight: 1.75 }}>
            Full system architecture is designed. Backend services are scaffolded. Kafka pipeline and ML anomaly detection are in active development.
          </p>
          <Link to="/" style={{ backgroundColor: '#ef4444', color: '#fff', textDecoration: 'none', borderRadius: '100px', padding: '12px 30px', fontSize: '0.82rem', fontWeight: 800, letterSpacing: '0.04em', display: 'inline-block' }}>
            ← Back to Portfolio
          </Link>
        </motion.div>

      </div>
    </div>
  )
}
